name: CI
on:
  push:
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -e .

      - name: Smoke run
        env:
          # säkerställer icke-interaktiv körning i CI
          CI: "1"
        run: python main.py

      - name: Verify
        run: |
          python verify.py
          test -f progress/receipt.json

      - name: Upload receipt & report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lesson-artifacts
          path: |
            progress/receipt.json
            reports/*.json
            notebooks/run_everything_REPORT.html
